### ISSUE TITLE
pkg-config error on installing cairo on Macs (pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist.)

### ISSUE THREAD

**Issue by andymeneely** [rcairo/rcairo#49]
One of my users reported this: https://github.com/andymeneely/squib/issues/232

Looks like it was on installing Cairo. I noticed that the pkg-config gem was recently released (Aug 6) - could it be an issue there?

**Comment by kou** [comment]
@choboy11 Could you show the followings?

```console
% pkg-config --print-requires cairo
% pkg-config --print-requires-private cairo
% ruby -r pkg-config/version -e 'p PKGConfig::VERSION'
% ruby -r mkmf -r pkg-config -e 'PKGConfig.have_package("cairo")'
```

**Comment by choboy11** [comment]
@kou Here it is:
'''
RaviAir:~ ravi$ pkg-config --print-requires cairo
RaviAir:~ ravi$ pkg-config --print-requires-private cairo
gobject-2.0
glib-2.0 >= 2.14
pixman-1 >= 0.30.0
fontconfig >= 2.2.95
freetype2 >= 9.7.3
libpng
RaviAir:~ ravi$ ruby -r pkg-config/version -e 'p PKGConfig::VERSION'
"1.2.4"
RaviAir:~ ravi$ ruby -r mkmf -r pkg-config -e 'PKGConfig.have_package("cairo")'
checking for cairo... yes
/Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist. (RuntimeError)
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:196:in `declaration'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:211:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:215:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:214:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:214:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:452:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.4/lib/pkg-config.rb:499:in `have_package'
	from -e:1:in `<main>'

'''

**Comment by kou** [comment]
Thanks. Could you provide more information?

```console
% pkg-config --print-requires libpng
% pkg-config --debug zlib
```

**Comment by choboy11** [comment]
sure: 

```
RaviAir:~ ravi$ pkg-config --print-requires libpng
zlib
RaviAir:~ ravi$ pkg-config --debug zlib
no output option set, defaulting to --exists
Error printing disabled by default due to use of output options --exists, --atleast/exact/max-version, --list-all or no output option at all. Value of --print-errors: 0
Error printing disabled
Adding virtual 'pkg-config' package to list of known packages
Looking for package 'zlib'
Looking for package 'zlib-uninstalled'
Reading 'zlib' from file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.10/zlib.pc'
Parsing package file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.10/zlib.pc'
  line>prefix=/usr
 Variable declaration, 'prefix' has value '/usr'
  line>exec_prefix=${prefix}
 Variable declaration, 'exec_prefix' has value '/usr'
  line>libdir=${exec_prefix}/lib
 Variable declaration, 'libdir' has value '/usr/lib'
  line>sharedlibdir=${libdir}
 Variable declaration, 'sharedlibdir' has value '/usr/lib'
  line>includedir=${prefix}/include
 Variable declaration, 'includedir' has value '/usr/include'
  line>
  line>Name: zlib
  line>Description: zlib compression library
  line>Version: 1.2.5
  line>
  line>Requires:
  line>Libs: -L${libdir} -L${sharedlibdir} -lz
  line>Cflags: -I${includedir}
Path position of 'zlib' is 4
Adding 'zlib' to list of known packages
Package zlib has -I/usr/include in Cflags
Removing -I/usr/include from cflags for zlib
Package zlib has -L /usr/lib in Libs
Removing -L /usr/lib from libs for zlib
Package zlib has -L /usr/lib in Libs
Removing -L /usr/lib from libs for zlib
```

**Comment by kou** [comment]
Thanks. It seems that Homebrew starts bundling .pc files for system libraries.

I've released a new pkg-config gem that supports it. Run `gem install pkg-config` and try again.

**Comment by choboy11** [comment]
Thanks for all your time and help. I ran `gem install pkg-config` and `pkg-config` installed no problems.
Then I tried `gem install squib` and had the same error that has been happening. I also tried `rvm implode` and then reinstalled rvm but this didn't seem to work either. Could it be i'm making a mistake when installing? Here is when I was installing the gems:

```
RaviAir:~ ravi$ gem install pkg-config
Successfully installed pkg-config-1.2.5
Parsing documentation for pkg-config-1.2.5
Installing ri documentation for pkg-config-1.2.5
Done installing documentation for pkg-config after 0 seconds
1 gem installed
RaviAir:~ ravi$ gem install squib
Building native extensions.  This could take a while...
ERROR:  Error installing squib:
	ERROR: Failed to build gem native extension.

    current directory: /Users/ravi/.rvm/gems/ruby-2.4.0/gems/cairo-1.15.9/ext/cairo
/Users/ravi/.rvm/rubies/ruby-2.4.0/bin/ruby -r ./siteconf20170810-27399-bg2s6g.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/ravi/.rvm/rubies/ruby-2.4.0/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist. (RuntimeError)
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:196:in `declaration'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:211:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:215:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:214:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:214:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:461:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:508:in `have_package'
	from extconf.rb:52:in `required_pkg_config_package'
	from extconf.rb:60:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ravi/.rvm/gems/ruby-2.4.0/extensions/x86_64-darwin-14/2.4.0/cairo-1.15.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ravi/.rvm/gems/ruby-2.4.0/gems/cairo-1.15.9 for inspection.
Results logged to /Users/ravi/.rvm/gems/ruby-2.4.0/extensions/x86_64-darwin-14/2.4.0/cairo-1.15.9/gem_make.out
RaviAir:~ ravi$ 
```

**Comment by kou** [comment]
Umm. What is the output of the following command?

```console
% ruby -r mkmf -r pkg-config -e 'p PKGConfig::VERSION; PKGConfig.have_package("cairo")'
"1.2.5"
checking for cairo... yes
```

**Comment by andymeneely** [comment]
FWIW I can't reproduce this on my Mac. Even with a `brew update` and starting clean. I do use rbenv, but I don't know that that's the difference.

**Comment by choboy11** [comment]
Thank you for the replies.
Here it is:
```
RaviAir:~ ravi$ ruby -r mkmf -r pkg-config -e 'p PKGConfig::VERSION; PKGConfig.have_package("cairo")'
"1.2.5"
checking for cairo... yes
/Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist. (RuntimeError)
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:196:in `declaration'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:211:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:145:in `cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:215:in `block in collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:214:in `collect'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:214:in `collect_cflags'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:461:in `cflags_only_other'
	from /Users/ravi/.rvm/gems/ruby-2.4.0/gems/pkg-config-1.2.5/lib/pkg-config.rb:508:in `have_package'
	from -e:1:in `<main>'
```

I'm going over the installation instructions to make sure i didn't miss anything.. also it seems I can download other gems, and i can do tutorials for ruby on mac, if that's of any use.

**Comment by kou** [comment]
Umm...

```console
% ruby -v -r pp -r pkg-config -e 'pp PackageConfig.new("cairo").paths'
% sw_vers -productVersion
```

**Comment by choboy11** [comment]
```
RaviAir:~ ravi$ ruby -v -r pp -r pkg-config -e 'pp PackageConfig.new("cairo").paths'
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin14]
["/usr/local/lib/pkgconfig", "/usr/local/lib/pkgconfig", "/usr/lib/pkgconfig"]
RaviAir:~ ravi$ sw_vers -productVersion
10.12.6
RaviAir:~ ravi$ 

```

**Comment by kou** [comment]
Please them:

```console
% brew --prefix
% which pkg-config
% brew list | grep pkg-config
```

**Comment by choboy11** [comment]
Ok, 

```
RaviAir:~ ravi$ brew --prefix
/usr/local
RaviAir:~ ravi$ which pkg-config
/usr/local/bin/pkg-config
RaviAir:~ ravi$ brew list | grep pkg-config
pkg-config
RaviAir:~ ravi$ 
```

**Comment by kou** [comment]
Thanks. I realized Homebrew repository path may be different with Homebre prefix.
I've released pkg-config 1.2.6. Please try it.

**Comment by choboy11** [comment]
Yes it worked! Thank you so much for your help.

**Comment by wkirby** [comment]
I've updated to `1.2.6` and I'm experiencing _essentially_ identical output to @choboy11. The only difference I can discern is that I'm on the High Sierra public beta — but I'm not sure that should have an effect here.

```
$ gem install squib
Building native extensions.  This could take a while...
ERROR:  Error installing squib:
	ERROR: Failed to build gem native extension.

    current directory: /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cairo-1.15.9/ext/cairo
/Users/wyattkirby/.rbenv/versions/2.4.1/bin/ruby -r ./siteconf20170815-56736-gxa4xl.rb extconf.rb
checking for GCC... yes
checking for Win32 OS... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/wyattkirby/.rbenv/versions/2.4.1/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist. (RuntimeError)
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:196:in `declaration'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:145:in `cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:211:in `collect'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:145:in `cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:215:in `block in collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:214:in `collect'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:214:in `collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:472:in `cflags_only_other'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:519:in `have_package'
	from extconf.rb:52:in `required_pkg_config_package'
	from extconf.rb:60:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/cairo-1.15.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/cairo-1.15.9 for inspection.
Results logged to /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-16/2.4.0-static/cairo-1.15.9/gem_make.out
```

```
$ ruby -r mkmf -r pkg-config -e 'p PKGConfig::VERSION; PKGConfig.have_package("cairo")'
"1.2.6"
checking for cairo... yes
/Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist. (RuntimeError)
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:196:in `declaration'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:210:in `collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:145:in `cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:212:in `block in collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:211:in `collect'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:211:in `collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:145:in `cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:215:in `block in collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:214:in `collect'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:214:in `collect_cflags'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:154:in `cflags_only_other'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:472:in `cflags_only_other'
	from /Users/wyattkirby/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/pkg-config-1.2.6/lib/pkg-config.rb:519:in `have_package'
	from -e:1:in `<main>'
```

```
$ ruby -v -r pp -r pkg-config -e 'pp PackageConfig.new("cairo").paths'
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
["/usr/local/lib/pkgconfig", "/usr/local/lib/pkgconfig", "/usr/lib/pkgconfig"]
```

```
$ sw_vers -productVersion
10.13
```

```
$ brew --prefix
/usr/local
```

```
$ which pkg-config
/usr/local/bin/pkg-config
```

```
$ brew list | grep pkg-config
pkg-config
```

**Comment by kou** [comment]
Please show the following:

```console
$ brew --repository
```

**Comment by wkirby** [comment]
```
$ brew --repository
/usr/local/Homebrew
```

**Comment by wkirby** [comment]
```
$ ls -la /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig
total 0
drwxr-xr-x  13 wyattkirby  admin  416 Jun 16 10:55 .
drwxr-xr-x  12 wyattkirby  admin  384 Jul 31 17:48 ..
drwxr-xr-x   8 wyattkirby  admin  256 Jun 16 10:55 10.10
drwxr-xr-x   8 wyattkirby  admin  256 Jun 16 10:55 10.11
drwxr-xr-x   8 wyattkirby  admin  256 Jun 16 10:55 10.12
drwxr-xr-x   8 wyattkirby  admin  256 Jul 31 17:48 10.13
lrwxr-xr-x   1 wyattkirby  admin    4 Jun 16 10:55 10.4 -> 10.5
drwxr-xr-x   4 wyattkirby  admin  128 Jun 16 10:55 10.5
drwxr-xr-x   4 wyattkirby  admin  128 Jun 16 10:55 10.6
drwxr-xr-x   4 wyattkirby  admin  128 Jun 16 10:55 10.7
drwxr-xr-x   8 wyattkirby  admin  256 Jun 16 10:55 10.8
drwxr-xr-x   8 wyattkirby  admin  256 Jun 16 10:55 10.9
drwxr-xr-x   4 wyattkirby  admin  128 Jun 16 10:55 fuse
```

**Comment by kou** [comment]
Thanks. Please try pkg-config 1.2.7.

**Comment by wkirby** [comment]
Thanks for your help!

**Comment by smanolloff** [comment]
Same issue here :/ Can you please help?

```
$ ruby -r mkmf -r pkg-config -e 'p PKGConfig::VERSION; PKGConfig.have_package("cairo")'
"1.2.7"
checking for cairo... yes
/Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:299:in `parse_pc': .pc for zlib doesn't exist. (RuntimeError)
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:196:in `declaration'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:210:in `collect_cflags'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:145:in `cflags'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:212:in `block in collect_cflags'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:211:in `collect'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:211:in `collect_cflags'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:145:in `cflags'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:215:in `block in collect_cflags'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:214:in `collect'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:214:in `collect_cflags'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:154:in `cflags_only_other'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:472:in `cflags_only_other'
  from /Users/simo/.rvm/gems/ruby-2.1.5/gems/pkg-config-1.2.7/lib/pkg-config.rb:519:in `have_package'
  from -e:1:in `<main>'
```

```
$ ruby -v -r pp -r pkg-config -e 'pp PackageConfig.new("cairo").paths' 
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
["/usr/local/lib/pkgconfig",
 "/usr/local/lib/pkgconfig",
 "/usr/lib/pkgconfig",
 "/usr/X11/lib/pkgconfig",
 "/opt/X11/lib/pkgconfig"]
```

```
$ sw_vers -productVersion
10.12.5
```

```
$ brew --prefix  
/usr/local
```

```
$ which pkg-config
/usr/local/bin/pkg-config
```

```
brew list | grep pkg-config
pkg-config
```

```
$ brew info pkg-config
pkg-config: stable 0.29.2 (bottled)
Manage compile and link flags for libraries
https://freedesktop.org/wiki/Software/pkg-config/
/usr/local/Cellar/pkg-config/0.29.2 (11 files, 627KB) *
  Poured from bottle on 2017-04-25 at 12:06:06
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb
```

```
brew --repository
/usr/local/Homebrew
```

```
ls -la /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig
total 8
drwxr-xr-x  13 simo  admin  442 Jul  6 16:33 .
drwxr-xr-x  12 simo  admin  408 Oct 19 14:34 ..
drwxr-xr-x   8 simo  admin  272 Apr 25 11:42 10.10
drwxr-xr-x   8 simo  admin  272 Apr 25 11:42 10.11
drwxr-xr-x   8 simo  admin  272 Apr 25 11:42 10.12
drwxr-xr-x   8 simo  admin  272 Aug  1 13:17 10.13
lrwxr-xr-x   1 simo  admin    4 Apr 25 11:42 10.4 -> 10.5
drwxr-xr-x   4 simo  admin  136 Apr 25 11:42 10.5
drwxr-xr-x   4 simo  admin  136 Apr 25 11:42 10.6
drwxr-xr-x   4 simo  admin  136 Apr 25 11:42 10.7
drwxr-xr-x   8 simo  admin  272 Apr 25 11:42 10.8
drwxr-xr-x   8 simo  admin  272 Apr 25 11:42 10.9
drwxr-xr-x   4 simo  admin  136 Apr 25 11:42 fuse
```

```
$ gem list pkg-config

*** LOCAL GEMS ***

pkg-config (1.2.7)
```

**Comment by kou** [comment]
Try pkg-config 1.2.8.

**Comment by smanolloff** [comment]
🍺  installation now goes without errors, thanks you!

**Comment by zurfarosa** [comment]
I'm getting an identical error to @choboy11 and @wkirby. Could you help?

```
Users-Air:~ zurfarosa$ ruby -r mkmf -r pkg-config -e 'p PKGConfig::VERSION; PKGConfig.have_package("cairo")'
"1.3.1"
checking for cairo... yes
Traceback (most recent call last):
	10: from -e:1:in `<main>'
	 9: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:522:in `have_package'
	 8: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:475:in `cflags_only_other'
	 7: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:154:in `cflags_only_other'
	 6: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:211:in `collect_cflags'
	 5: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:211:in `collect'
	 4: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:212:in `block in collect_cflags'
	 3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:145:in `cflags'
	 2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:210:in `collect_cflags'
	 1: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:196:in `declaration'
/usr/local/Cellar/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/pkg-config-1.3.1/lib/pkg-config.rb:299:in `parse_pc': .pc for fontconfig doesn't exist. (RuntimeError)
```

```
Users-Air:~ zurfarosa$ ruby -v -r pp -r pkg-config -e 'pp PackageConfig.new("cairo").paths' 
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
["/usr/local/lib/pkgconfig",
 "/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.13",
 "/usr/local/lib/pkgconfig",
 "/usr/lib/pkgconfig"]
```

```
sw_vers -productVersion
10.13
```

```
Users-Air:~ zurfarosa$ brew --prefix
/usr/local
```

```
Users-Air:~ zurfarosa$ which pkg-config
/usr/local/bin/pkg-config

```
```
Users-Air:~ zurfarosa$ brew list | grep pkg-config
pkg-config

```
```
Users-Air:~ zurfarosa$ brew info pkg-config
pkg-config: stable 0.29.2 (bottled)
Manage compile and link flags for libraries
https://freedesktop.org/wiki/Software/pkg-config/
/usr/local/Cellar/pkg-config/0.29.2 (11 files, 627.2KB) *
  Poured from bottle on 2018-08-19 at 16:52:37
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pkg-config.rb
```

```
Users-Air:~ zurfarosa$ brew --repository
/usr/local/Homebrew
```

```
Users-Air:~ zurfarosa$ ls -la /usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig
total 0
drwxr-xr-x  14 zurfarosa  admin  448 19 Aug 17:17 .
drwxr-xr-x  11 zurfarosa  admin  352 19 Aug 17:17 ..
drwxr-xr-x   8 zurfarosa  admin  256 13 Mar 19:14 10.10
drwxr-xr-x   8 zurfarosa  admin  256 13 Mar 19:14 10.11
drwxr-xr-x   8 zurfarosa  admin  256 13 Mar 19:14 10.12
drwxr-xr-x   8 zurfarosa  admin  256 13 Mar 19:14 10.13
drwxr-xr-x   8 zurfarosa  admin  256 19 Aug 17:17 10.14
lrwxr-xr-x   1 zurfarosa  admin    4 13 Mar 19:14 10.4 -> 10.5
drwxr-xr-x   4 zurfarosa  admin  128 13 Mar 19:14 10.5
drwxr-xr-x   4 zurfarosa  admin  128 13 Mar 19:14 10.6
drwxr-xr-x   4 zurfarosa  admin  128 13 Mar 19:14 10.7
drwxr-xr-x   8 zurfarosa  admin  256 13 Mar 19:14 10.8
drwxr-xr-x   8 zurfarosa  admin  256 13 Mar 19:14 10.9
drwxr-xr-x   4 zurfarosa  admin  128 13 Mar 19:14 fuse
```

```
Users-Air:~ zurfarosa$ gem list pkg-config
*** LOCAL GEMS ***
pkg-config (1.3.1)
```

```
Users-Air:~ zurfarosa$ ruby --version
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
```
