### ISSUE TITLE
Error installing on Heroku: `stderr@@GLIBC_2.2.5' can not be used

### ISSUE THREAD

**Issue by Bodacious** [rcairo/rcairo#72]
Hi all,

I'm having trouble trying to deploy an app to Heroku. The error seems to be caused by a failure in the Cairo gem make script.

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:
current directory:
/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/gems/cairo-1.17.5/ext/cairo
/tmp/build_c62652fd/vendor/ruby-2.7.3/bin/ruby -I
/tmp/build_c62652fd/vendor/ruby-2.7.3/lib/ruby/2.7.0 -r
./siteconf20210623-803-1w1w2pl.rb extconf.rb
checking for GCC... yes
checking for Homebrew... no
checking for cairo version (>= 1.2.0)... yes
checking for cairo-ft... yes
checking for macOS... no
checking for HAVE_RUBY_ST_H in ruby.h... yes
checking for HAVE_RUBY_IO_H in ruby.h... yes
checking for rb_errinfo() in ruby.h... yes
checking for rb_gc_adjust_memory_usage() in ruby.h... yes
checking for enum ruby_value_type in ruby.h... yes
creating Makefile
remote:
current directory:
/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/gems/cairo-1.17.5/ext/cairo
make "DESTDIR=" clean
remote:
current directory:
/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/gems/cairo-1.17.5/ext/cairo
make "DESTDIR="
compiling rb_cairo.c
compiling rb_cairo_constants.c
compiling rb_cairo_context.c
compiling rb_cairo_device.c
compiling rb_cairo_exception.c
compiling rb_cairo_font_extents.c
compiling rb_cairo_font_face.c
compiling rb_cairo_font_options.c
compiling rb_cairo_glyph.c
compiling rb_cairo_io.c
compiling rb_cairo_matrix.c
compiling rb_cairo_path.c
compiling rb_cairo_pattern.c
compiling rb_cairo_private.c
compiling rb_cairo_quartz_surface.c
compiling rb_cairo_rectangle.c
compiling rb_cairo_region.c
compiling rb_cairo_scaled_font.c
compiling rb_cairo_surface.c
compiling rb_cairo_text_cluster.c
compiling rb_cairo_text_extents.c
linking shared-object cairo.so
/usr/bin/ld:
/tmp/build_c62652fd/.apt/usr/lib/x86_64-linux-gnu/libcairo.a(cairo-boxes.o):
relocation R_X86_64_PC32 against symbol `stderr@@GLIBC_2.2.5' can not be used
when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:262: cairo.so] Error 1
remote:
make failed, exit code 2
remote:
Gem files will remain installed in
/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/gems/cairo-1.17.5 for inspection.
Results logged to
/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/cairo-1.17.5/gem_make.out
remote:
An error occurred while installing cairo (1.17.5), and Bundler cannot continue.
Make sure that `gem install cairo -v '1.17.5' --source 'https://rubygems.org/'`
succeeds before bundling.
remote:
In Gemfile:
  gtk3 was resolved to 3.4.4, which depends on
    gdk3 was resolved to 3.4.4, which depends on
      pango was resolved to 3.4.4, which depends on
        cairo-gobject was resolved to 3.4.4, which depends on
          cairo
remote:
remote:  !
Failed to install gems via Bundler.
remote:  !
Push rejected, failed to compile Ruby app.
remote:
Push failed
```

Cairo `libcairo2-dev` is installed on the system using apt-get.

Any idea what's going wrong here?

**Comment by kou** [comment]
Could you show the followings?

* `/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/cairo-1.17.5/gem_make.out`
* `/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/cairo-1.17.5/Makefile`
* `/tmp/build_c62652fd/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/cairo-1.17.5/mkmf.log`
* `/tmp/build_c62652fd/.apt/usr/lib/x86_64-linux-gnu/pkgconfig/cairo.pc`

**Comment by Bodacious** [comment]
@kou As far as I know, I can't access those files on Heroku. They're not available when I access the server directly. 

When I try installing the gem manually I get the following:

```
ERROR:  Error installing cairo:
	ERROR: Failed to build gem native extension.

    current directory: /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/cairo-1.17.5/ext/cairo
/app/vendor/ruby-2.7.3/bin/ruby -I /app/vendor/ruby-2.7.3/lib/ruby/2.7.0 -r ./siteconf20210625-6-f5fdz.rb extconf.rb
checking for GCC... yes
checking for Homebrew... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/app/vendor/ruby-2.7.3/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:389:in `parse_pc': .pc doesn't exist: <gobject-2.0> (PackageConfig::NotFoundError)
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:233:in `declaration'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:178:in `requires_private'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:509:in `block in all_required_packages'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:259:in `collect_requires'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:265:in `block in collect_requires'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `each'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `collect_requires'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:508:in `all_required_packages'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:283:in `collect_cflags'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:191:in `cflags_only_other'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:569:in `cflags_only_other'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:616:in `have_package'
	from extconf.rb:42:in `required_pkg_config_package'
	from extconf.rb:50:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/cairo-1.17.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/cairo-1.17.5 for inspection.
Results logged to /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/cairo-1.17.5/gem_make.out
```

gem_make.out:

```
current directory: /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/cairo-1.17.5/ext/cairo
/app/vendor/ruby-2.7.3/bin/ruby -I /app/vendor/ruby-2.7.3/lib/ruby/2.7.0 -r ./siteconf20210625-250-9i4i51.rb extconf.rb
checking for GCC... yes
checking for Homebrew... no
checking for cairo version (>= 1.2.0)... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/app/vendor/ruby-2.7.3/bin/$(RUBY_BASE_NAME)
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
/app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:389:in `parse_pc': .pc doesn't exist: <gobject-2.0> (PackageConfig::NotFoundError)
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:233:in `declaration'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:178:in `requires_private'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:509:in `block in all_required_packages'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:259:in `collect_requires'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:265:in `block in collect_requires'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `each'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:260:in `collect_requires'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:508:in `all_required_packages'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:283:in `collect_cflags'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:191:in `cflags_only_other'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:569:in `cflags_only_other'
	from /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/gems/pkg-config-1.4.6/lib/pkg-config.rb:616:in `have_package'
	from extconf.rb:42:in `required_pkg_config_package'
	from extconf.rb:50:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /app/vendor/ruby-2.7.3/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/cairo-1.17.5/mkmf.log

extconf failed, exit code 1
```

mkmf.log:

```
checking for GCC... -------------------- yes

"gcc -o conftest -I/app/vendor/ruby-2.7.3/include/ruby-2.7.0/x86_64-linux -I/app/vendor/ruby-2.7.3/include/ruby-2.7.0/ruby/backward -I/app/vendor/ruby-2.7.3/include/ruby-2.7.0 -I.    -O3 -g -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC conftest.c  -L. -L/app/vendor/ruby-2.7.3/lib -Wl,-rpath,/app/vendor/ruby-2.7.3/lib -L. -fstack-protector-strong -rdynamic -Wl,-export-dynamic     -Wl,-rpath,'/../lib' -Wl,-rpath,'/../lib' -lruby  -lm   -lc"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

"gcc -I/app/vendor/ruby-2.7.3/include/ruby-2.7.0/x86_64-linux -I/app/vendor/ruby-2.7.3/include/ruby-2.7.0/ruby/backward -I/app/vendor/ruby-2.7.3/include/ruby-2.7.0 -I.    -O3 -g -Wall -Wextra -Wdeprecated-declarations -Wduplicated-cond -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wwrite-strings -Wimplicit-fallthrough=0 -Wmissing-noreturn -Wno-cast-function-type -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-packed-bitfield-compat -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wunused-variable  -fPIC   -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: /*top*/
4: #ifndef __GNUC__
5: # error
6: |:/ === __GNUC__ undefined === /:|
7: #endif
/* end */

--------------------

checking for Homebrew... -------------------- no

--------------------

have_package: checking for cairo version (>= 1.2.0)... -------------------- yes

--------------------
```

I can't seem to access `pkgconfig/cairo.pc` on the Heroku instance, despite it being confirmed in the build log:
