### ISSUE TITLE
Cairo::Path#line_to always raises an exception

### ISSUE THREAD

**Issue by toshia** [rcairo/rcairo#83]
- ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
- rcairo >= 1.17.7 (v1.17.6 not affected)
- cairo 1.17.13

in <= rcairo v1.17.7 ( https://github.com/rcairo/rcairo/commit/3206c61fff39d73c869cd353ae55d11fdb0974e4 ), rcairo raises exception in this code:

```ruby
require 'cairo'

class PathTest < Test::Unit::TestCase
  def test_line_to
    path = Cairo::Path.new
    path.line_to(1.0, 1.0)
    assert(path)
  end
end
```

result:
```
Error: test_line_to(PathTest): NoMethodError: undefined method `line_to' for nil:NilClass
/home/toshi/.rbenv/versions/3.0.6/lib/ruby/gems/3.0.0/gems/forwardable-1.3.3/lib/forwardable.rb:238:in `line_to'                                              
/home/toshi/Project/rcairo/test/test_path.rb:6:in `test_line_to'
```

Same thing happens in other delegated methods.
The same thing happened when I created a `Cairo::Path` via `Cairo::Context#copy_path` .

**Comment by kou** [comment]
Oh, sorry.
I'll fix this in a few weeks.

BTW, it seems that this feature of `cairo::Path` has been broken since I implemented it at 2007...
(It didn't raise an error but it didn't do useful result...)
